# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias docker-pause='docker pause $(/usr/local/bin/docker ps -f status=running -q)'
alias docker-unpause='docker unpause $(/usr/local/bin/docker ps -f status=paused -q)'
alias dup='docker-compose up'
alias de='docker-compose exec'
alias dew='docker-compose exec web'
alias code='code-insiders'
alias gco='git checkout'
alias gst='git status'
alias gunwip='git log -n 1 | grep -q -c "\-\-wip\-\-" && git reset HEAD~1'
alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'

alias dup='docker-compose up'
alias de='docker-compose exec'

alias be='bundle exec'
alias bet='TEST_LOGGING_ENABLED=true bundle exec'
alias download-udemy="youtube-dl --cookies ~/code/udemy/udemy-cookies.txt -o './%(playlist_title)s/%(chapter_number)s - %(chapter)s - %(playlist_index)s - %(title)s.%(ext)s'"

function chpwd() {
	pwd >| ~/.whereami
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
autoload -Uz compinit
compinit

export AWS_OKTA_BACKEND=pass

export PATH="/snap/bin:$PATH"

export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
export PATH=$PATH:'/mnt/c/Program Files/Docker/Docker/resources/bin'
alias code='/mnt/c/Users/enviable/AppData/Local/Programs/Microsoft\ VS\ Code\ Insiders/bin/code-insiders'
alias pbcopy='/mnt/c/Windows/System32/clip.exe'
# source <(kubectl completion zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
